from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .views import (
    AsignacionCreateView,
    AsignacionUpdateView,
    BolsaCompensarView,
    BolsaMovimientosView,
    BolsaSaldoUsuarioView,
    BolsaSaldosView,
    GoogleCallbackView,
    GoogleConnectUrlView,
    GoogleDisconnectView,
    GoogleSyncMeView,
    GoogleSyncSemanaView,
    IntercambioAceptarView,
    IntercambioCancelarView,
    IntercambioCreateView,
    IntercambioRechazarView,
    IntercambiosMiasView,
    MeView,
    MisAsignacionesView,
    RegisterView,
    SemanaDetailView,
    SemanaGenerarAnioView,
    SemanaGenerarMesView,
    SemanaListCreateView,
    SemanaPublicarView,
    SemanaRotacionView,
    UsuariosActivosView,
)

urlpatterns = [
    path("auth/register", RegisterView.as_view()),
    path("auth/login", TokenObtainPairView.as_view()),
    path("auth/refresh", TokenRefreshView.as_view()),
    path("auth/me", MeView.as_view()),
    path("usuarios", UsuariosActivosView.as_view()),
    path("semanas", SemanaListCreateView.as_view()),
    path("semanas/rotacion", SemanaRotacionView.as_view()),
    path("semanas/generar-mes", SemanaGenerarMesView.as_view()),
    path("semanas/generar-anio", SemanaGenerarAnioView.as_view()),
    path("semanas/<uuid:semana_id>", SemanaDetailView.as_view()),
    path("semanas/<uuid:semana_id>/publicar", SemanaPublicarView.as_view()),
    path("asignaciones-tarde", AsignacionCreateView.as_view()),
    path("asignaciones-tarde/mias", MisAsignacionesView.as_view()),
    path("asignaciones-tarde/<uuid:asignacion_id>", AsignacionUpdateView.as_view()),
    path("intercambios", IntercambioCreateView.as_view()),
    path("intercambios/mias", IntercambiosMiasView.as_view()),
    path("intercambios/<uuid:intercambio_id>/aceptar", IntercambioAceptarView.as_view()),
    path("intercambios/<uuid:intercambio_id>/rechazar", IntercambioRechazarView.as_view()),
    path("intercambios/<uuid:intercambio_id>/cancelar", IntercambioCancelarView.as_view()),
    path("bolsa/saldos", BolsaSaldosView.as_view()),
    path("bolsa/saldos/<uuid:usuario_id>", BolsaSaldoUsuarioView.as_view()),
    path("bolsa/movimientos", BolsaMovimientosView.as_view()),
    path("bolsa/compensar", BolsaCompensarView.as_view()),
    path("calendar/google/connect-url", GoogleConnectUrlView.as_view()),
    path("calendar/google/callback", GoogleCallbackView.as_view()),
    path("calendar/google/sync/semana/<uuid:semana_id>", GoogleSyncSemanaView.as_view()),
    path("calendar/google/sync/me", GoogleSyncMeView.as_view()),
    path("calendar/google/disconnect", GoogleDisconnectView.as_view()),
]
