# Generated by Django 6.0.2 on 2026-04-08 12:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado')], default='empleado', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('crear_intercambio', 'Crear intercambio'), ('aceptar_intercambio', 'Aceptar intercambio'), ('actualizar_bolsa', 'Actualizar bolsa'), ('sync_calendar', 'Sync calendar')], max_length=40)),
                ('entidad', models.CharField(max_length=50)),
                ('id_entidad', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='BolsaDiasSaldo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saldo_dias_a_favor_de_a', models.PositiveIntegerField(default=0)),
                ('saldo_dias_a_favor_de_b', models.PositiveIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_a', to=settings.AUTH_USER_MODEL)),
                ('usuario_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario_a', 'usuario_b')},
            },
        ),
        migrations.CreateModel(
            name='CalendarioSemanal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveSmallIntegerField()),
                ('numero_semana', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('fecha_inicio_semana', models.DateField()),
                ('fecha_fin_semana', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20)),
            ],
            options={
                'ordering': ['-anio', '-numero_semana'],
                'unique_together': {('anio', 'numero_semana')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionTarde',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miercoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=20)),
                ('hora_inicio', models.TimeField(default='14:00')),
                ('hora_fin', models.TimeField(default='22:00')),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('intercambiado', 'Intercambiado')], default='asignado', max_length=20)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_tarde', to=settings.AUTH_USER_MODEL)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.calendariosemanal')),
            ],
            options={
                'ordering': ['semana__anio', 'semana__numero_semana', 'dia'],
                'unique_together': {('semana', 'usuario', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='IntegracionGoogleCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_calendar_id', models.CharField(default='primary', max_length=200)),
                ('sincronizacion_activa', models.BooleanField(default=False)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('state_token', models.CharField(blank=True, max_length=255)),
                ('ultima_sync', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudIntercambio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('dia', 'Dia'), ('semana', 'Semana')], max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('modo_compensacion', models.CharField(choices=[('inmediata', 'Inmediata'), ('bolsa', 'Bolsa')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('es_compensacion', models.BooleanField(default=False)),
                ('dias_estimados', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('asignacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_destino', to='core.asignaciontarde')),
                ('asignacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_origen', to='core.asignaciontarde')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BolsaDiasMovimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dias', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('genera_deuda', 'Genera deuda'), ('compensa_deuda', 'Compensa deuda')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destino_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('origen_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_generados', to=settings.AUTH_USER_MODEL)),
                ('saldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.bolsadiassaldo')),
                ('solicitud_intercambio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bolsa', to='core.solicitudintercambio')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
