# Generated by Django 6.0.4 on 2026-04-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaevento',
            name='tipo_evento',
            field=models.CharField(choices=[('crear_intercambio', 'Crear intercambio'), ('aceptar_intercambio', 'Aceptar intercambio'), ('actualizar_bolsa', 'Actualizar bolsa'), ('sync_calendar', 'Sync calendar'), ('publicar_semana', 'Publicar semana')], max_length=40),
        ),
    ]
