# Generated by Django 6.0.4 on 2026-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_auditoriaevento_tipo_evento"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudintercambio",
            name="rol_solicitante_compensacion",
            field=models.CharField(
                choices=[("acreedor", "Acreedor"), ("deudor", "Deudor")],
                default="acreedor",
                max_length=20,
            ),
        ),
    ]
